### Create New Class
POST http://localhost:3003/mission
Content-Type: application/json

{
            "name": "Freud",
            "start_date": "2018-04-30",
            "end_date": "2020-04-30",
            "module": "1",
            "period": "full_time"
}