### Create New Class
POST http://localhost:3003/mission
Content-Type: application/json

{
            "name": "Freud",
            "start_date": "30/04/2017",
            "end_date": "30/01/2021",
            "module": "1",
            "period": "full_time"
}